"""Quantum-model interchange and solver interfaces for QE-ADAPT workflows."""

from qeanalyzer.quantum.active_space import (
    ActiveSpace,
    ActiveSpaceSelector,
    BandIndexSelector,
    EnergyWindowSelector,
    ExplicitOrbitalSelector,
    OccupationSelector,
    create_active_space_selector,
    select_active_space,
)
from qeanalyzer.quantum.adapt_bridge import QuantumRunResult, QuantumSolver
from qeanalyzer.quantum.clifford_bridge import (
    CliffordQCACASESolver,
    CliffordQCADAPTACASESolver,
    CliffordQCADAPTSolver,
    clifford_qc_available,
    clifford_qc_subspace_available,
)
from qeanalyzer.quantum.comparison import (
    ArmOutcome,
    ComparisonSolver,
    SolverArm,
    SolverComparison,
    compare_solvers,
)
from qeanalyzer.quantum.fcidump import parse_fcidump, read_fcidump, write_fcidump
from qeanalyzer.quantum.feedback import (
    ActiveSpaceFeedbackPolicy,
    HubbardUFeedbackPolicy,
    OccupationFeedbackPolicy,
    QuantumFeedbackPolicy,
    apply_quantum_feedback,
)
from qeanalyzer.quantum.hamiltonian import (
    MaterialHamiltonian,
    build_active_space_hamiltonian,
    build_band_model_hamiltonian,
    build_hubbard_hamiltonian,
    build_integral_hamiltonian,
)
from qeanalyzer.quantum.solver_api import (
    ADAPTVQESolver,
    ExactDiagonalizationSolver,
    SimulatedADAPTVQESolver,
    SolverSpec,
    available_solvers,
    create_quantum_solver,
    describe_solvers,
    normalize_solver_type,
    register_solver,
    solve_active_space,
    solver_names,
    unregister_solver,
)

__all__ = [
    "ActiveSpace",
    "ActiveSpaceFeedbackPolicy",
    "ActiveSpaceSelector",
    "ADAPTVQESolver",
    "apply_quantum_feedback",
    "ArmOutcome",
    "available_solvers",
    "BandIndexSelector",
    "build_active_space_hamiltonian",
    "build_band_model_hamiltonian",
    "build_hubbard_hamiltonian",
    "build_integral_hamiltonian",
    "clifford_qc_available",
    "clifford_qc_subspace_available",
    "CliffordQCACASESolver",
    "CliffordQCADAPTACASESolver",
    "CliffordQCADAPTSolver",
    "compare_solvers",
    "ComparisonSolver",
    "create_active_space_selector",
    "create_quantum_solver",
    "describe_solvers",
    "EnergyWindowSelector",
    "ExactDiagonalizationSolver",
    "ExplicitOrbitalSelector",
    "HubbardUFeedbackPolicy",
    "MaterialHamiltonian",
    "normalize_solver_type",
    "OccupationFeedbackPolicy",
    "OccupationSelector",
    "parse_fcidump",
    "QuantumFeedbackPolicy",
    "QuantumRunResult",
    "QuantumSolver",
    "read_fcidump",
    "register_solver",
    "select_active_space",
    "SimulatedADAPTVQESolver",
    "solve_active_space",
    "solver_names",
    "SolverArm",
    "SolverComparison",
    "SolverSpec",
    "unregister_solver",
    "write_fcidump",
]
